
    version: "3.8"

    services:
        zenv-express:
            build: ./
            image: zenv-express
            environment:
                - REDIS_HOST=redis-server
                - MYSQL_HOST=mysql-server
            networks:
                - Zenv-network
            ports:
                - 4321:3000
    
        redis-server:
            image: redis:7-alpine
            networks:
                - Zenv-network
    
        mysql-server:
            image: mysql:8
            restart: always
            environment:
                MYSQL_ROOT_PASSWORD: test
            networks:
                - Zenv-network
            volumes:
                - ./gitFolder/mysql:/docker-entrypoint-initdb.d
    networks:
        Zenv-network: