
    FROM node:18-slim

    # Create app directory
    WORKDIR /usr/src/app
    
    # Install app dependencies
    # A wildcard is used to ensure both package.json AND package-lock.json are copied
    # where available (npm@5+)
     COPY gitFolder/ ./
    
     RUN npm install
    # If you are building your code for production
    # RUN npm ci --omit=dev
    
    
    EXPOSE 3000
    
    CMD [ "node", "app.js"]