name: Unit Test

on:
    workflow_dispatch: # 手動觸發

jobs:
    deploy:
        runs-on: ubuntu-latest # 執行環境在Linux最新版

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3 # 檢查和檢出程式碼

            - name: Unit tests for Express-and-TCPserver
              run: cd Express-and-TCPserver && npm install && npm test # 在 Express-and-TCPserver 資料夾執行單元測試
